spring.application.name=CloudDocs

spring.datasource.url=jdbc:postgresql://localhost:5432/clouddocs
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.locations=classpath:sql
spring.flyway.enabled=true
