spring:
  application:
    name: CloudDocs

  datasource:
    url: jdbc:postgresql://localhost:5432/clouddocs
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:sql
    enabled: true

media:
  aws:
    region: ${AWS_REGION:us-east-1}
    bucket-name: ${MEDIA_S3_BUCKET:}
    queue-url: ${MEDIA_SQS_QUEUE_URL:}

jwt:
  secret: Zm9vYmFyYmF6cXV4ZXhhbXBsZXNlY3JldGZvcmp3dHNpZ25pbmc=
  expiration: 86400000
  refresh-expiration: 604800000
cloudinary:
  cloud_name: dq220j08p
  api_key: 173816746428851
  api_secret: MywkFenL-1s3pCOBkbqK8qxSQdI
  profiles:
      active: awss3
    cloud:
      config:
        server:
          awss3:
            region: us-east-1
            bucket: bucket1