[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RewanshChoudhary", email = "rewanshchoudhary57@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.99",
    "psycopg[binary]>=3.2.4",
    "python-dotenv>=1.0.1",
]

[project.scripts]
worker = "src.worker:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
